# behaviors:
#   CrossTheRoad:
#     trainer_type: ppo
#     hyperparameters:
#       batch_size: 10
#       buffer_size: 100
#       learning_rate: 3.0e-4
#       beta: 1.0e-4
#       epsilon: 0.2
#       lambd: 0.99
#       num_epoch: 3
#       learning_rate_schedule: linear
#     network_settings:
#       normalize: false
#       hidden_units: 128
#       num_layers: 2
#     reward_signals:
#       extrinsic:
#         gamma: 0.99
#         strength: 1.0
#     max_steps: 15000000
#     time_horizon: 64
#     summary_freq: 5000

behaviors:
  CrossTheRoad:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64  # Increased from 10
      buffer_size: 2048  # Increased from 100
      learning_rate: 3.0e-4
      beta: 5.0e-3  # Increased from 1.0e-4
      epsilon: 0.2
      lambd: 0.95  # Slightly decreased from 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true  # Changed from false
      hidden_units: 256  # Increased from 128
      num_layers: 3  # Increased from 2
    max_steps: 20000000  # Increased from 15000000
    time_horizon: 128  # Increased from 64
    summary_freq: 10000  # Increased from 5000